export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  verify: '/verify',
  // claim: '/dashboard/claim',
  myCertificate: '/my-certificate',
  issue: '/issue',
  batchIssue: '/batch-issue',
  // overview: '/dashboard',
  // account: '/dashboard/account',
  // customers: '/dashboard/customers',
  // integrations: '/dashboard/integrations',
  // settings: '/dashboard/settings',
  errors: { notFound: '/errors/not-found' },
} as const;
